version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:5173

  backend:
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app

volumes:
  air_bnc:
